### PR TITLE
fixed issue with removing breakpoints

### LINKED ISSUE #212: Can't remove breakpoints
While the debugged program is running, breakpoints can't be removed (that is, juCi acknowledges the breakpoint removal by removing line highlighting, but the actual breakpoint isn't removed and LLDB stops on it anyway).

Quick debugging reveals that it's not removed because `breakpoint_path==file_path` is false at `debug_clang.cc:465` because `breakpoint_path` is `"/home/milleniumbug/dokumenty/PROJEKTY/NotMine/jucipp/build/debug/../../src/debug_clang.cc"` and `file_path` is `"/home/milleniumbug/dokumenty/PROJEKTY/NotMine/jucipp/src/debug_clang.cc"`

I assume using `boost::filesystem::equivalent` instead would fix the problem.

### PR DESCRIPTION
**Pull request by milleniumbug**
Fixes #212

### CODE REVIEW

File: src/debug_clang.cc [hunk 1]
```diff
@@ -463,6 +463,7 @@ void Debug::Clang::remove_breakpoint(const boost::filesystem::path &file_path, i
             auto file_spec=line_entry.GetFileSpec();
             boost::filesystem::path breakpoint_path=file_spec.GetDirectory();
             breakpoint_path/=file_spec.GetFilename();
+            breakpoint_path = boost::filesystem::canonical(breakpoint_path);
```
Comment (eidheim) [inline src/debug_clang.cc]: See for instance https://github.com/cppit/jucipp/blob/master/src/juci.cc#L29. Add `error_code ec` and check if `!ec`.

Comment (milleniumbug) [inline src/debug_clang.cc]: And then...? What should be the appropriate response if the path handed out by LLDB doesn't exist? Is it because they got it wrong? Is it because someone removed it in the TOCTTU fashion? Should we crash? I suppose not. Should we ignore it? Sure, but then what is the state of the program? After all, the highlighting is removed by GUI somewhere else, so we can't just log it and move on. I ask because I seriously don't know.

Comment (eidheim) [inline src/debug_clang.cc]: lldb is not 100% stable, at least not the earlier versions, it's just to be on the safe side. No need in my opinion to handle the error in this case, as it probably never will happen.
